version: '3'
services:
  php:
    build:
      context: ./php
    container_name: app_php
    volumes:
      - './app:/var/www/html'
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
  mysql:
    build:
      context: ./mysql
    container_name: app_db
    restart: unless-stopped
    volumes:
      - 'mysql_data:/var/lib/mysql'
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  nginx:
    build:
      context: ./nginx
    container_name: app_web
    volumes:
      - './app:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/templates:/etc/nginx/templates'
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    depends_on:
        - php
    environment:
        - NGINX_HOST=localhost
        - NGINX_PORT=${NGINX_PORT}

volumes:
  mysql_data:
